//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoeRankingTracker.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoeRankingTracker.Resources.Translations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find league.
        /// </summary>
        public static string CannotFindLeague {
            get {
                return ResourceManager.GetString("CannotFindLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character name.
        /// </summary>
        public static string CharacterName {
            get {
                return ResourceManager.GetString("CharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters found with account name {0}.
        /// </summary>
        public static string CharactersFoundForAccount {
            get {
                return ResourceManager.GetString("CharactersFoundForAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a template.
        /// </summary>
        public static string ChooseTemplate {
            get {
                return ResourceManager.GetString("ChooseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ClassRank {
            get {
                return ResourceManager.GetString("ClassRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POE Ranking Tracker - Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deads ahead.
        /// </summary>
        public static string DeadsAhead {
            get {
                return ResourceManager.GetString("DeadsAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date : {0}.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank {0}.
        /// </summary>
        public static string ExperienceAhead {
            get {
                return ResourceManager.GetString("ExperienceAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank {0}.
        /// </summary>
        public static string ExperienceBehind {
            get {
                return ResourceManager.GetString("ExperienceBehind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP/h.
        /// </summary>
        public static string ExperiencePerHour {
            get {
                return ResourceManager.GetString("ExperiencePerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve league.
        /// </summary>
        public static string FailedToRetrieveLeague {
            get {
                return ResourceManager.GetString("FailedToRetrieveLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve leagues.
        /// </summary>
        public static string FailedToRetrieveLeagues {
            get {
                return ResourceManager.GetString("FailedToRetrieveLeagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string GlobalRank {
            get {
                return ResourceManager.GetString("GlobalRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide advanced options.
        /// </summary>
        public static string HideAdvancedOptions {
            get {
                return ResourceManager.GetString("HideAdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string LanguageFrench {
            get {
                return ResourceManager.GetString("LanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League/Race.
        /// </summary>
        public static string League {
            get {
                return ResourceManager.GetString("League", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No characters found for account {0}.
        /// </summary>
        public static string NoCharactersFoundForAccount {
            get {
                return ResourceManager.GetString("NoCharactersFoundForAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview (dummy values).
        /// </summary>
        public static string PreviewLabel {
            get {
                return ResourceManager.GetString("PreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh templates.
        /// </summary>
        public static string RefreshTemplates {
            get {
                return ResourceManager.GetString("RefreshTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Id.
        /// </summary>
        public static string SessionId {
            get {
                return ResourceManager.GetString("SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Id is correct.
        /// </summary>
        public static string SessionIdCorrect {
            get {
                return ResourceManager.GetString("SessionIdCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Id is incorrect.
        /// </summary>
        public static string SessionIdIncorrect {
            get {
                return ResourceManager.GetString("SessionIdIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Id is recommended.
        /// </summary>
        public static string SessionIdMissing {
            get {
                return ResourceManager.GetString("SessionIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show progress bar.
        /// </summary>
        public static string ShowProgressBar {
            get {
                return ResourceManager.GetString("ShowProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show rank by class.
        /// </summary>
        public static string ShowRankByClass {
            get {
                return ResourceManager.GetString("ShowRankByClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date : {0}.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open URL.
        /// </summary>
        public static string UnableToOpenUrl {
            get {
                return ResourceManager.GetString("UnableToOpenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve characters.
        /// </summary>
        public static string UnableToRetrieveCharacters {
            get {
                return ResourceManager.GetString("UnableToRetrieveCharacters", resourceCulture);
            }
        }
    }
}
